### ISSUE TITLE
Logs during the graceful shutdown

### ISSUE THREAD

**Issue by dcaraxes** [michurin/human-readable-json-logging#3]
I have no expertise in this matter - but is it possible to make pplog depend on the context of the application? For example, when launching an application that has a graceful shutdown implemented, with Ctrl - C (sigint), pplog shuts down without displaying application logs.

**Comment by michurin** [comment]
Hi @dcaraxes! Could you provide simple way to reproduce the issue? Shell command or codesnippet?

**Comment by dcaraxes** [comment]
> Hi @dcaraxes! Could you provide simple way to reproduce the issue? Shell command or codesnippet?
> 
> And could you pleas show the output of `pplog -v`? Are you sure you are using the latest version of `pplog`?

This is just being solved in the pull request https://github.com/michurin/human-readable-json-logging/pull/15 . I have already tried that version on Mac OS and everything works as I expected.
